export const permissionCatalog = [
  ['hospital.read', 'Read hospital details and settings'],
  ['hospital.manage', 'Manage hospital details and settings'],
  ['role.read', 'Read roles and permissions'],
  ['role.manage', 'Manage roles and permissions'],
  ['location.read', 'Read hospital locations'],
  ['location.manage', 'Manage hospital locations'],
  ['bed.read', 'Read care locations'],
  ['bed.manage', 'Manage care locations'],
  ['qr.generate', 'Generate care location QR codes'],
  ['qr.rotate', 'Rotate care location QR codes'],
  ['qr.revoke', 'Revoke care location QR codes'],
  ['staff.read', 'Read staff records'],
  ['staff.manage', 'Manage staff memberships and assignments'],
  ['service.read', 'Read the service catalog'],
  ['service.manage', 'Manage the service catalog'],
  ['request.read', 'Read service requests'],
  ['request.assign', 'Assign service requests'],
  ['request.accept', 'Accept service requests'],
  ['request.start', 'Start service requests'],
  ['request.complete', 'Complete service requests'],
  ['request.transfer', 'Transfer service requests'],
  ['request.cancel', 'Cancel service requests'],
  ['routing.manage', 'Manage routing rules'],
  ['sla.manage', 'Manage SLA policies'],
  ['audit.read', 'Read audit history'],
  ['analytics.read', 'Read analytics'],
] as const;

export type PermissionKey = (typeof permissionCatalog)[number][0];
